name: 'Helfi KASKO Config'
type: module
core_version_requirement: ^10 || ^11
dependencies:
  - helfi_kasko_content:helfi_kasko_content
  - helfi_platform_config:helfi_tpr_config
  - helfi_platform_config:helfi_platform_config
