_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'easy_breadcrumb.settings:home_segment_title'
  - 'field.storage.paragraph.field_calculator:settings.allowed_values'
  - 'hdbt_admin_tools.site_settings'
  - 'helfi_calculator.settings'
  - 'system.site:page.front'
